apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: test-logging.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: test-logging-client-service
              servicePort: 3000
          - path: /api/user/?(.*)
            backend:
              serviceName: test-logging-users-service
              servicePort: 3002
          - path: /api/payment/?(.*)
            backend:
              serviceName: test-logging-payment-service
              servicePort: 3001